#!/usr/bin/env python3

"""
KISS V5.6.12.3.1
METHODOLOGY AUDIT ONLY

Purpose:
    One transition -> one warning.

This version deliberately does NOT:
    - generate global warning episodes
    - cluster thousands of warnings
    - run survival checkpoints
    - run reverse analysis
    - modify the trading engine

It only validates the warning-assignment methodology.

Rules:
    1. Build direct LONG->SHORT and SHORT->LONG transitions.
    2. For each transition, inspect only its own pre-transition window.
    3. Generate warning candidates inside that window.
    4. Select ONE warning for that transition.
    5. Never allow one warning to belong to multiple transitions.
    6. Print the complete audit and stop.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Optional

from db import get_db_connection


# ============================================================
# CONFIG
# ============================================================

TIMEFRAME_30M = "30m"
TIMEFRAME_5M = "5m"

LOOKBACK_MINUTES = 360

# Minimum evidence for a warning.
ADVERSE_PCT = 0.20
NET_NEGATIVE_PCT = 0.20

# Require either structure damage OR two independent deterioration
# signals. This prevents a warning from being generated by every
# tiny negative candle.
MIN_WARNING_SCORE = 2

# Structure lookback.
STRUCTURE_BARS = 3


# ============================================================
# DATA
# ============================================================

@dataclass
class Candle:
    timestamp: datetime
    close: float
    high: float
    low: float


@dataclass
class Transition:
    symbol: str
    direction_from: str
    direction_to: str
    timestamp: datetime
    price: float


@dataclass
class Warning:
    transition_key: str
    timestamp: datetime
    age_minutes: float
    score: int
    adverse_pct: float
    net_pct: float
    consecutive_adverse: int
    structure_break: bool
    reasons: str


# ============================================================
# DB
# ============================================================

def load_candles(symbol: str, timeframe: str) -> list[Candle]:
    conn, cur = get_db_connection()

    try:
        cur.execute(
            """
            SELECT
                timestamp,
                close,
                high,
                low
            FROM candles
            WHERE symbol = %s
              AND timeframe = %s
            ORDER BY timestamp
            """,
            (symbol, timeframe),
        )

        rows = cur.fetchall()

    finally:
        cur.close()
        conn.close()

    result = []

    for row in rows:
        ts = row["timestamp"]

        if not isinstance(ts, datetime):
            ts = datetime.fromisoformat(str(ts))

        result.append(
            Candle(
                timestamp=ts,
                close=float(row["close"]),
                high=float(row["high"]),
                low=float(row["low"]),
            )
        )

    return result


# ============================================================
# FAST INDEX
# ============================================================

def build_index(candles: list[Candle]) -> dict[datetime, int]:
    return {
        candle.timestamp: i
        for i, candle in enumerate(candles)
    }


def nearest_index(
    candles: list[Candle],
    target: datetime,
) -> Optional[int]:

    if not candles:
        return None

    lo = 0
    hi = len(candles) - 1

    while lo <= hi:
        mid = (lo + hi) // 2

        ts = candles[mid].timestamp

        if ts == target:
            return mid

        if ts < target:
            lo = mid + 1
        else:
            hi = mid - 1

    candidates = []

    if 0 <= lo < len(candles):
        candidates.append(lo)

    if 0 <= hi < len(candles):
        candidates.append(hi)

    if not candidates:
        return None

    return min(
        candidates,
        key=lambda i: abs(
            (candles[i].timestamp - target).total_seconds()
        ),
    )


# ============================================================
# MARKET STATE
# ============================================================

def market_state(
    closes: list[float],
    i: int,
    window: int = 20,
    band: float = 0.002,
) -> str:

    if i < window:
        return "FLAT"

    ma = sum(closes[i - window:i]) / window

    price = closes[i]

    if price > ma * (1.0 + band):
        return "LONG"

    if price < ma * (1.0 - band):
        return "SHORT"

    return "FLAT"


# ============================================================
# TRANSITIONS
# ============================================================

def build_transitions(
    symbol: str,
    candles: list[Candle],
) -> list[Transition]:

    if not candles:
        return []

    closes = [c.close for c in candles]

    states = [
        market_state(closes, i)
        for i in range(len(candles))
    ]

    transitions = []

    for i in range(1, len(states)):

        old = states[i - 1]
        new = states[i]

        # Only direct directional transitions.
        if old == "LONG" and new == "SHORT":
            transitions.append(
                Transition(
                    symbol=symbol,
                    direction_from="LONG",
                    direction_to="SHORT",
                    timestamp=candles[i].timestamp,
                    price=candles[i].close,
                )
            )

        elif old == "SHORT" and new == "LONG":
            transitions.append(
                Transition(
                    symbol=symbol,
                    direction_from="SHORT",
                    direction_to="LONG",
                    timestamp=candles[i].timestamp,
                    price=candles[i].close,
                )
            )

    return transitions


# ============================================================
# STRUCTURE TEST
# ============================================================

def structure_break(
    candles: list[Candle],
    i: int,
    direction: str,
) -> bool:

    if i < STRUCTURE_BARS:
        return False

    current = candles[i].close

    previous = [
        candles[j].close
        for j in range(
            i - STRUCTURE_BARS,
            i,
        )
    ]

    if len(previous) < STRUCTURE_BARS:
        return False

    if direction == "LONG":

        # Long thesis damaged when current close
        # breaks below the recent structure.
        return current < min(previous)

    if direction == "SHORT":

        # Short thesis damaged when current close
        # breaks above recent structure.
        return current > max(previous)

    return False


# ============================================================
# WARNING CANDIDATE
# ============================================================

def make_warning_candidate(
    candles: list[Candle],
    i: int,
    original_direction: str,
) -> Optional[Warning]:

    if i <= 0:
        return None

    entry_price = candles[i].close

    if entry_price <= 0:
        return None

    # --------------------------------------------------------
    # Measure movement against the original trend.
    # --------------------------------------------------------

    start = max(0, i - 12)

    old_price = candles[start].close

    if old_price <= 0:
        return None

    move_pct = (
        (entry_price - old_price)
        / old_price
        * 100.0
    )

    if original_direction == "LONG":

        adverse_pct = max(
            0.0,
            -move_pct,
        )

        net_pct = move_pct

    else:

        adverse_pct = max(
            0.0,
            move_pct,
        )

        net_pct = -move_pct

    # --------------------------------------------------------
    # Consecutive adverse closes.
    # --------------------------------------------------------

    consecutive = 0

    j = i

    while j > 0:

        previous_close = candles[j - 1].close
        current_close = candles[j].close

        if original_direction == "LONG":
            adverse = current_close < previous_close
        else:
            adverse = current_close > previous_close

        if not adverse:
            break

        consecutive += 1
        j -= 1

    # --------------------------------------------------------
    # Structure.
    # --------------------------------------------------------

    broken = structure_break(
        candles,
        i,
        original_direction,
    )

    # --------------------------------------------------------
    # Score.
    # --------------------------------------------------------

    score = 0
    reasons = []

    if adverse_pct >= ADVERSE_PCT:
        score += 1
        reasons.append("ADVERSE_020")

    if abs(net_pct) >= NET_NEGATIVE_PCT and net_pct < 0:
        score += 1
        reasons.append("NET_NEGATIVE_020")

    if consecutive >= 2:
        score += 1
        reasons.append("CONSEC_2")

    if broken:
        score += 1
        reasons.append("STRUCTURE_BREAK")

    if score < MIN_WARNING_SCORE:
        return None

    return Warning(
        transition_key="",
        timestamp=candles[i].timestamp,
        age_minutes=0.0,
        score=score,
        adverse_pct=adverse_pct,
        net_pct=net_pct,
        consecutive_adverse=consecutive,
        structure_break=broken,
        reasons=",".join(reasons),
    )


# ============================================================
# ONE WARNING PER TRANSITION
# ============================================================

def select_one_warning(
    transition: Transition,
    candles: list[Candle],
) -> Optional[Warning]:

    t0 = transition.timestamp

    window_start = t0 - timedelta(
        minutes=LOOKBACK_MINUTES
    )

    # --------------------------------------------------------
    # Find the candle immediately before T0.
    # --------------------------------------------------------

    t0_i = nearest_index(
        candles,
        t0,
    )

    if t0_i is None:
        return None

    # Never inspect T0 or anything after T0.
    last_i = t0_i - 1

    if last_i < 1:
        return None

    # --------------------------------------------------------
    # Find first candle in the allowed window.
    # --------------------------------------------------------

    start_i = nearest_index(
        candles,
        window_start,
    )

    if start_i is None:
        start_i = 0

    if start_i > last_i:
        return None

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # Scan chronologically.
    #
    # We want the FIRST legitimate warning,
    # not the strongest warning and not the last warning.
    # --------------------------------------------------------

    for i in range(start_i, last_i + 1):

        candidate = make_warning_candidate(
            candles,
            i,
            transition.direction_from,
        )

        if candidate is None:
            continue

        candidate.transition_key = (
            f"{transition.symbol}|"
            f"{transition.direction_from}->"
            f"{transition.direction_to}|"
            f"{transition.timestamp.isoformat()}"
        )

        candidate.age_minutes = (
            t0 - candidate.timestamp
        ).total_seconds() / 60.0

        return candidate

    return None


# ============================================================
# AUDIT
# ============================================================

def main():

    symbols = [
        "NVDA",
        "AAPL",
        "MSFT",
        "AMZN",
        "TSLA",
        "SPY",
        "QQQ",
        "BTCUSD",
        "ETHUSD",
        "SOLUSD",
        "LINKUSD",
    ]

    all_transitions: list[Transition] = []
    assigned: list[tuple[Transition, Warning]] = []

    print()
    print("=" * 78)
    print("KISS V5.6.12.3.1 — METHODOLOGY AUDIT")
    print("=" * 78)
    print()
    print("RULE: ONE TRANSITION -> ONE WARNING")
    print(f"LOOKBACK: {LOOKBACK_MINUTES} minutes")
    print(f"MIN WARNING SCORE: {MIN_WARNING_SCORE}")
    print()
    print("NO SURVIVAL ANALYSIS")
    print("NO GLOBAL WARNING EPISODES")
    print("NO CLUSTERING")
    print()

    for symbol in symbols:

        print(
            f"[{symbol}] loading candles...",
            flush=True,
        )

        try:
            candles = load_candles(
                symbol,
                TIMEFRAME_5M,
            )

        except Exception as exc:
            print(
                f"[{symbol}] ERROR loading candles: {exc}"
            )
            continue

        print(
            f"[{symbol}] 5m candles={len(candles)}",
            flush=True,
        )

        if len(candles) < 30:
            continue

        transitions = build_transitions(
            symbol,
            candles,
        )

        print(
            f"[{symbol}] transitions={len(transitions)}",
            flush=True,
        )

        all_transitions.extend(transitions)

        for transition in transitions:

            warning = select_one_warning(
                transition,
                candles,
            )

            if warning is None:
                continue

            assigned.append(
                (
                    transition,
                    warning,
                )
            )

            print(
                f"{symbol} "
                f"{transition.direction_from}->"
                f"{transition.direction_to} "
                f"T0={transition.timestamp} "
                f"WARNING={warning.timestamp} "
                f"age={warning.age_minutes:.0f}m "
                f"score={warning.score} "
                f"adv={warning.adverse_pct:.3f}% "
                f"net={warning.net_pct:.3f}% "
                f"consec={warning.consecutive_adverse} "
                f"structure={warning.structure_break} "
                f"reasons={warning.reasons}",
                flush=True,
            )

    # ========================================================
    # GLOBAL AUDIT
    # ========================================================

    transition_keys = []

    for t in all_transitions:

        key = (
            f"{t.symbol}|"
            f"{t.direction_from}->"
            f"{t.direction_to}|"
            f"{t.timestamp.isoformat()}"
        )

        transition_keys.append(key)

    warning_keys = [
        w.transition_key
        for _, w in assigned
    ]

    unique_transitions = set(
        transition_keys
    )

    unique_warning_assignments = set(
        warning_keys
    )

    duplicate_warning_assignments = (
        len(warning_keys)
        - len(unique_warning_assignments)
    )

    long_short = [
        t for t in all_transitions
        if t.direction_from == "LONG"
        and t.direction_to == "SHORT"
    ]

    short_long = [
        t for t in all_transitions
        if t.direction_from == "SHORT"
        and t.direction_to == "LONG"
    ]

    assigned_long_short = [
        t for t, _ in assigned
        if t.direction_from == "LONG"
        and t.direction_to == "SHORT"
    ]

    assigned_short_long = [
        t for t, _ in assigned
        if t.direction_from == "SHORT"
        and t.direction_to == "LONG"
    ]

    print()
    print("=" * 78)
    print("GLOBAL METHODOLOGY AUDIT")
    print("=" * 78)

    print(
        f"Transitions found:          {len(all_transitions)}"
    )

    print(
        f"Unique transitions:         {len(unique_transitions)}"
    )

    print(
        f"Warnings assigned:          {len(assigned)}"
    )

    print(
        f"Unique warning assignments: {len(unique_warning_assignments)}"
    )

    print(
        f"Duplicate assignments:      {duplicate_warning_assignments}"
    )

    print(
        f"Unassigned transitions:     "
        f"{len(all_transitions) - len(assigned)}"
    )

    print()
    print(
        f"LONG -> SHORT:              "
        f"{len(long_short)}"
    )

    print(
        f"LONG -> SHORT assigned:     "
        f"{len(assigned_long_short)}"
    )

    print(
        f"SHORT -> LONG:              "
        f"{len(short_long)}"
    )

    print(
        f"SHORT -> LONG assigned:     "
        f"{len(assigned_short_long)}"
    )

    # ========================================================
    # AGE SUMMARY
    # ========================================================

    ages = [
        w.age_minutes
        for _, w in assigned
    ]

    if ages:

        ages_sorted = sorted(ages)

        median_age = ages_sorted[
            len(ages_sorted) // 2
        ]

        print()
        print(
            f"Warning lead min:           "
            f"{min(ages):.1f}m"
        )

        print(
            f"Warning lead median:        "
            f"{median_age:.1f}m"
        )

        print(
            f"Warning lead max:           "
            f"{max(ages):.1f}m"
        )

    # ========================================================
    # METHODOLOGY VERDICT
    # ========================================================

    print()
    print("=" * 78)
    print("METHODOLOGY VERDICT")
    print("=" * 78)

    if duplicate_warning_assignments != 0:
        print(
            "FAIL: duplicate warning assignments detected."
        )

    elif len(assigned) != len(
        unique_warning_assignments
    ):
        print(
            "FAIL: warning uniqueness failed."
        )

    else:
        print(
            "PASS: every assigned warning belongs to exactly "
            "one transition."
        )

    print()
    print(
        "This script intentionally stops here."
    )
    print(
        "No checkpoint analysis has been run."
    )
    print()


if __name__ == "__main__":
    main()
