#!/usr/bin/env python3

"""
EXPERIMENT #31
NVDA V-SHAPE / RECOVERY GEOMETRY

Research only.

Purpose:
    Determine whether the actual shape of the price reversal after a
    30m transition contains information that a simple entry-trail
    percentage cannot capture.

No production code is modified.
No trading orders are placed.

Uses the existing KISS trailing-entry/exit research trade files
generated by Experiment #30.

Important:
    This experiment is descriptive.
    It does NOT create or promote a trading rule.
"""

from pathlib import Path
import pandas as pd
import numpy as np


ROOT = Path.cwd()
EXP30_DIR = ROOT / "kiss" / "results" / "exp30_nvda_transition_match"
OUT_DIR = ROOT / "kiss" / "results" / "exp31_nvda_v_shape_geometry"

OUT_DIR.mkdir(parents=True, exist_ok=True)

LEVELS = [
    ("025", "0.25%"),
    ("050", "0.50%"),
    ("075", "0.75%"),
    ("100", "1.00%"),
    ("125", "1.25%"),
    ("150", "1.50%"),
]

FILES = {
    code: EXP30_DIR / f"nvda_trades_entry_{code}.csv"
    for code, label in LEVELS
}


def pct_change(direction, start_price, price):
    if start_price == 0 or pd.isna(start_price) or pd.isna(price):
        return np.nan

    if direction == "LONG":
        return (price / start_price - 1.0) * 100.0

    return (start_price / price - 1.0) * 100.0


def classify_v(row):
    """
    Descriptive classification only.

    We deliberately avoid claiming that any class is good/bad.
    """

    depth = row["V_DEPTH_%"]
    recovery = row["RECOVERY_FROM_BOTTOM_%"]
    speed = row["RECOVERY_SPEED_%_PER_MIN"]
    pnl = row["P&L_%"]

    if pd.isna(depth):
        return "NO_GEOMETRY"

    if depth < 0.50:
        if recovery < 0.25:
            return "A_SHALLOW_WEAK"
        return "A_SHALLOW_RECOVERY"

    if speed >= 0.10:
        if pnl > 0:
            return "C_FAST_RECOVERY_WIN"
        return "C_FAST_RECOVERY_FAIL"

    if recovery >= 1.00:
        if pnl > 0:
            return "B_DEEP_STRONG_RECOVERY_WIN"
        return "B_DEEP_STRONG_RECOVERY_FAIL"

    if recovery >= 0.50:
        if pnl > 0:
            return "D_MODERATE_RECOVERY_WIN"
        return "D_MODERATE_RECOVERY_FAIL"

    if pnl > 0:
        return "E_WEAK_RECOVERY_WIN"

    return "E_WEAK_RECOVERY_FAIL"


def load_all_trails():
    frames = []

    for code, label in LEVELS:
        path = FILES[code]

        if not path.exists():
            raise FileNotFoundError(
                f"Missing Experiment #30 file:\n{path}\n\n"
                f"Run Experiment #30 first."
            )

        df = pd.read_csv(path)

        if "symbol" in df.columns:
            df = df[df["symbol"] == "NVDA"].copy()

        df["ENTRY_TRAIL_LABEL"] = label
        df["ENTRY_TRAIL_CODE"] = code

        frames.append(df)

    return pd.concat(frames, ignore_index=True)


def build_transition_table(all_df):
    key_cols = [
        "symbol",
        "transition_time_utc",
        "direction",
        "transition_from",
        "transition_to",
    ]

    # One row per transition, retaining the smallest-trail result
    # as the primary actual trade record when available.
    base = (
        all_df.sort_values(
            key_cols + ["ENTRY_TRAIL_CODE"]
        )
        .drop_duplicates(key_cols, keep="first")
        .copy()
    )

    base["transition_time_utc"] = pd.to_datetime(
        base["transition_time_utc"],
        utc=True,
    )

    base["entry_time_utc"] = pd.to_datetime(
        base["entry_time_utc"],
        utc=True,
    )

    base["entry_extreme_time_utc"] = pd.to_datetime(
        base["entry_extreme_time_utc"],
        utc=True,
    )

    base["exit_time_utc"] = pd.to_datetime(
        base["exit_time_utc"],
        utc=True,
    )

    # The existing trade files give us:
    #
    # transition price proxy = entry extreme
    #
    # The V is therefore measured from the transition direction
    # using entry_extreme as the observed adverse extreme.
    #
    # This is deliberately conservative: we are not inventing
    # intra-candle future information.

    def calculate_row(row):
        direction = row["direction"]
        extreme = row["entry_extreme"]
        entry = row["entry_price"]

        if direction == "LONG":
            v_depth = (
                (entry - extreme) / entry * 100.0
                if entry else np.nan
            )

            recovery = (
                (entry - extreme) / entry * 100.0
                if entry else np.nan
            )

        else:
            v_depth = (
                (extreme - entry) / entry * 100.0
                if entry else np.nan
            )

            recovery = (
                (extreme - entry) / entry * 100.0
                if entry else np.nan
            )

        return pd.Series(
            {
                "V_DEPTH_%": v_depth,
                "RECOVERY_FROM_BOTTOM_%": recovery,
            }
        )

    geom = base.apply(calculate_row, axis=1)
    base = pd.concat(
        [base.reset_index(drop=True), geom.reset_index(drop=True)],
        axis=1,
    )

    base["TIME_TO_BOTTOM_MIN"] = (
        base["entry_extreme_time_utc"]
        - base["transition_time_utc"]
    ).dt.total_seconds() / 60.0

    base["TIME_TO_ENTRY_MIN"] = (
        base["entry_time_utc"]
        - base["transition_time_utc"]
    ).dt.total_seconds() / 60.0

    base["RECOVERY_TIME_FROM_BOTTOM_MIN"] = (
        base["entry_time_utc"]
        - base["entry_extreme_time_utc"]
    ).dt.total_seconds() / 60.0

    base["RECOVERY_SPEED_%_PER_MIN"] = np.where(
        base["RECOVERY_TIME_FROM_BOTTOM_MIN"] > 0,
        base["RECOVERY_FROM_BOTTOM_%"]
        / base["RECOVERY_TIME_FROM_BOTTOM_MIN"],
        np.nan,
    )

    base["P&L_%"] = base["pnl_pct"]
    base["MFE_%"] = base["max_favorable_pct"]
    base["MAE_%"] = base["max_adverse_pct"]

    base["WIN"] = base["pnl_pct"] > 0

    base["V_CLASS"] = base.apply(classify_v, axis=1)

    return base


def print_header(title):
    print()
    print("=" * 120)
    print(title)
    print("=" * 120)


def main():
    print_header("EXPERIMENT #31")
    print("NVDA V-SHAPE / RECOVERY GEOMETRY")
    print()
    print("RESEARCH ONLY")
    print("Existing Experiment #30 output is used.")
    print("No production code is modified.")
    print()

    all_df = load_all_trails()

    print(f"Experiment #30 rows loaded : {len(all_df)}")

    geometry = build_transition_table(all_df)

    output = OUT_DIR / "nvda_v_shape_geometry.csv"
    geometry.to_csv(output, index=False)

    print()
    print(f"[OUTPUT] {output}")

    # ------------------------------------------------------------
    # PRIMARY TABLE
    # ------------------------------------------------------------

    print_header("PRIMARY V-SHAPE TABLE")

    cols = [
        "transition_time_utc",
        "direction",
        "transition_from",
        "transition_to",
        "V_DEPTH_%",
        "TIME_TO_BOTTOM_MIN",
        "RECOVERY_FROM_BOTTOM_%",
        "RECOVERY_TIME_FROM_BOTTOM_MIN",
        "RECOVERY_SPEED_%_PER_MIN",
        "TIME_TO_ENTRY_MIN",
        "P&L_%",
        "MFE_%",
        "MAE_%",
        "WIN",
        "V_CLASS",
    ]

    display = geometry[cols].copy()

    pd.set_option("display.max_rows", 200)
    pd.set_option("display.max_columns", 50)
    pd.set_option("display.width", 240)
    pd.set_option("display.float_format", lambda x: f"{x:8.3f}")

    print(display.to_string(index=False))

    # ------------------------------------------------------------
    # CLASS SUMMARY
    # ------------------------------------------------------------

    print_header("V-SHAPE CLASS SUMMARY")

    summary = (
        geometry.groupby("V_CLASS")
        .agg(
            cases=("V_CLASS", "size"),
            winners=("WIN", "sum"),
            avg_pnl=("P&L_%", "mean"),
            total_pnl=("P&L_%", "sum"),
            avg_depth=("V_DEPTH_%", "mean"),
            avg_recovery=("RECOVERY_FROM_BOTTOM_%", "mean"),
            avg_speed=("RECOVERY_SPEED_%_PER_MIN", "mean"),
            avg_mfe=("MFE_%", "mean"),
            avg_mae=("MAE_%", "mean"),
        )
        .reset_index()
    )

    summary["win_rate_%"] = (
        summary["winners"] / summary["cases"] * 100.0
    )

    print(summary.to_string(index=False))

    summary_path = OUT_DIR / "nvda_v_shape_class_summary.csv"
    summary.to_csv(summary_path, index=False)

    print()
    print(f"[OUTPUT] {summary_path}")

    # ------------------------------------------------------------
    # OUTCOME BY V DEPTH
    # ------------------------------------------------------------

    print_header("OUTCOME BY V DEPTH")

    geometry["DEPTH_BUCKET"] = pd.cut(
        geometry["V_DEPTH_%"],
        bins=[
            -np.inf,
            0.25,
            0.50,
            1.00,
            1.50,
            2.00,
            3.00,
            np.inf,
        ],
        labels=[
            "<0.25%",
            "0.25-0.50%",
            "0.50-1.00%",
            "1.00-1.50%",
            "1.50-2.00%",
            "2.00-3.00%",
            ">3.00%",
        ],
    )

    depth_summary = (
        geometry.groupby("DEPTH_BUCKET", observed=False)
        .agg(
            cases=("P&L_%", "size"),
            winners=("WIN", "sum"),
            avg_pnl=("P&L_%", "mean"),
            total_pnl=("P&L_%", "sum"),
            avg_recovery=("RECOVERY_FROM_BOTTOM_%", "mean"),
            avg_speed=("RECOVERY_SPEED_%_PER_MIN", "mean"),
        )
        .reset_index()
    )

    depth_summary["win_rate_%"] = (
        depth_summary["winners"]
        / depth_summary["cases"]
        * 100.0
    )

    print(depth_summary.to_string(index=False))

    depth_path = OUT_DIR / "nvda_v_shape_depth_summary.csv"
    depth_summary.to_csv(depth_path, index=False)

    print()
    print(f"[OUTPUT] {depth_path}")

    # ------------------------------------------------------------
    # RECOVERY SPEED
    # ------------------------------------------------------------

    print_header("OUTCOME BY RECOVERY SPEED")

    geometry["SPEED_BUCKET"] = pd.cut(
        geometry["RECOVERY_SPEED_%_PER_MIN"],
        bins=[
            -np.inf,
            0.02,
            0.05,
            0.10,
            0.20,
            np.inf,
        ],
        labels=[
            "<0.02%/min",
            "0.02-0.05",
            "0.05-0.10",
            "0.10-0.20",
            ">0.20",
        ],
    )

    speed_summary = (
        geometry.groupby("SPEED_BUCKET", observed=False)
        .agg(
            cases=("P&L_%", "size"),
            winners=("WIN", "sum"),
            avg_pnl=("P&L_%", "mean"),
            total_pnl=("P&L_%", "sum"),
            avg_depth=("V_DEPTH_%", "mean"),
            avg_recovery=("RECOVERY_FROM_BOTTOM_%", "mean"),
        )
        .reset_index()
    )

    speed_summary["win_rate_%"] = (
        speed_summary["winners"]
        / speed_summary["cases"]
        * 100.0
    )

    print(speed_summary.to_string(index=False))

    speed_path = OUT_DIR / "nvda_v_shape_speed_summary.csv"
    speed_summary.to_csv(speed_path, index=False)

    print()
    print(f"[OUTPUT] {speed_path}")

    # ------------------------------------------------------------
    # IMPORTANT: LOW-MFE LOSERS
    # ------------------------------------------------------------

    print_header("POSSIBLE NOISY-V CANDIDATES")
    print("Definition for inspection only:")
    print("MFE < 0.50% AND final P&L < 0")

    noisy = geometry[
        (geometry["MFE_%"] < 0.50)
        & (geometry["P&L_%"] < 0)
    ].copy()

    noisy = noisy.sort_values(
        ["P&L_%", "MFE_%"]
    )

    noisy_cols = [
        "transition_time_utc",
        "direction",
        "V_DEPTH_%",
        "TIME_TO_BOTTOM_MIN",
        "RECOVERY_FROM_BOTTOM_%",
        "RECOVERY_TIME_FROM_BOTTOM_MIN",
        "RECOVERY_SPEED_%_PER_MIN",
        "TIME_TO_ENTRY_MIN",
        "P&L_%",
        "MFE_%",
        "MAE_%",
        "V_CLASS",
    ]

    print(
        noisy[noisy_cols].to_string(index=False)
    )

    noisy_path = OUT_DIR / "nvda_possible_noisy_v_candidates.csv"
    noisy.to_csv(noisy_path, index=False)

    print()
    print(f"[OUTPUT] {noisy_path}")

    # ------------------------------------------------------------
    # STRONG WINNERS
    # ------------------------------------------------------------

    print_header("STRONG RECOVERY / WINNER CANDIDATES")
    print("Definition for inspection only:")
    print("P&L > 0 AND MFE >= 2.00%")

    strong = geometry[
        (geometry["P&L_%"] > 0)
        & (geometry["MFE_%"] >= 2.00)
    ].copy()

    strong = strong.sort_values(
        ["P&L_%"],
        ascending=False,
    )

    print(
        strong[noisy_cols].to_string(index=False)
    )

    strong_path = OUT_DIR / "nvda_strong_recovery_winners.csv"
    strong.to_csv(strong_path, index=False)

    print()
    print(f"[OUTPUT] {strong_path}")

    # ------------------------------------------------------------
    # TRAIL PRESENCE
    # ------------------------------------------------------------

    print_header("ENTRY-TRAIL PRESENCE FOR EACH TRANSITION")

    key_cols = [
        "symbol",
        "transition_time_utc",
        "direction",
        "transition_from",
        "transition_to",
    ]

    presence = []

    for key, group in all_df.groupby(key_cols, dropna=False):

        row = dict(zip(key_cols, key))

        present = []

        for code, label in LEVELS:
            if code in set(group["ENTRY_TRAIL_CODE"]):
                present.append(label)

        row["TRAILS_PRESENT"] = " | ".join(present)

        row["NUM_TRAILS_PRESENT"] = len(present)

        presence.append(row)

    presence_df = pd.DataFrame(presence)

    presence_path = OUT_DIR / "nvda_transition_trail_presence.csv"
    presence_df.to_csv(presence_path, index=False)

    print(presence_df.to_string(index=False))
    print()
    print(f"[OUTPUT] {presence_path}")

    # ------------------------------------------------------------
    # FINAL SUMMARY
    # ------------------------------------------------------------

    print_header("EXPERIMENT #31 COMPLETE")

    print("Questions this experiment is designed to answer:")
    print()
    print("1. Are the bad low-MFE trades structurally shallow V's?")
    print("2. Are profitable trades characterized by deeper but faster recovery?")
    print("3. Does recovery speed separate winners from losers?")
    print("4. Does time spent at the adverse extreme matter?")
    print("5. Are profitable V's being rejected by larger entry trails?")
    print()
    print("IMPORTANT:")
    print("These are research measurements only.")
    print("No entry threshold has been promoted.")
    print("No production strategy has been changed.")
    print()
    print(f"All Experiment #31 results:")
    print(f"  {OUT_DIR}")
    print()
    print("NEXT STEP:")
    print("Inspect the actual rows before deciding what Experiment #32 should test.")


if __name__ == "__main__":
    main()
